### ISSUE TITLE
VLC can't find aacs libraries.

### ISSUE THREAD

**Issue by lavadrop** [flathub/org.videolan.VLC.Plugin.makemkv#12]
I have all the needed plug-ins both VLC and makemkv and I can't open Blurays anymore. Used to work before. MakeMKV works fine on its own.
This is what I get from -vv
[vlc aacs error log.txt](https://github.com/flathub/org.videolan.VLC.Plugin.makemkv/files/12615266/vlc.aacs.error.log.txt)

**Comment by Nukleari** [comment]
I have the same issue, it seems like it tries to download a version of makemkv that is no longer up.
https://www.makemkv.com/download/makemkv-bin-1.14.4.tar.gz
https://www.makemkv.com/download/makemkv-oss-1.14.4.tar.gz
The latest version is 1.17.4.
Gonna look into it in a bit more detail tomorrow.

**Comment by Nukleari** [comment]
There is a new branch that has the correct version of makemkv, installing any other version won't actually download anything, as links for the older versions are no longer online.
You can't install the latest version using discover, to install the latest branch type ``flatpak install runtime/org.videolan.VLC.Plugin.makemkv/x86_64/3-22.08`` in the terminal and follow the install instructions
for me it still doesn't work. I get the following error in vlc:
```
Blu-ray error:
Blu-ray Disc is corrupted.
Your input can't be opened:
VLC is unable to open the MRL 'bluray:///dev/sr0'. Check the log for details.
```
the putput of ``flatpak run org.videolan.VLC -vv`` is:
[vlc.log](https://github.com/flathub/org.videolan.VLC.Plugin.makemkv/files/12671553/vlc.log)
I get a different return code.
DVD playback works in the flatpak version of vlc.
The standalone flatpak of MakeMKV can't find the disk drive.
I tried the same usb-c dock with the same drive on my notebook that has all the necessary stuff installed from aur and it works.

**Comment by Nukleari** [comment]
The second error I got was because the sg kernel module wasn't loaded. on the steamdeck I was able to load it with ``modprobe sg`` but since it worked for you before just installing the latest version of the plugin using the terminal should fix the problem.

**Comment by Thalionquses** [comment]
I have the same error on Fedora 39. I've installed all possible versions of the makemkv plugin but VLC always shows the error message. But it used to work on older versions.
[vlc.log](https://github.com/flathub/org.videolan.VLC.Plugin.makemkv/files/13884519/vlc.log)

**Comment by Nukleari** [comment]
the latest version ``3-23.08`` works for me. ``3-22.08`` should also work as well, because it's been updated to use makeMKV 1.17.5.
Try uninstalling any version of the plugin and install with: 
```
flatpak install runtime/org.videolan.VLC.Plugin.makemkv/x86_64/3-23.08
```

**Comment by Thalionquses** [comment]
Thanks for your reply, I've removed every version of it and then reinstalled 3-23.08 but it still fails with the same error:

```
david@zbook-firefly14-g7:~$ flatpak run org.videolan.VLC 
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[0000561e61f7f6d0] main libvlc: VLC wird mit dem Standard-Interface ausgeführt. Benutzen Sie 'cvlc', um VLC ohne Interface zu verwenden.
Gtk-Message: 13:24:14.246: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:24:14.246: Failed to load module "pk-gtk-module"
Gtk-Message: 13:24:14.247: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:24:14.247: Failed to load module "pk-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: Could not open network socket
[0000561e62014c50] main playlist: playlist is empty
aacs.c:121: No usable AACS libraries found!
dec.c:197: aacs_open() failed: -1!
[00007f9890001130] libbluray demux: First play: 1, Top menu: 1
HDMV Titles: 105, BD-J Titles: 0, Other: 0
david@zbook-firefly14-g7:~$ flatpak install runtime/org.videolan.VLC.Plugin.makemkv/x86_64/3-23.08
Suchen nach Übereinstimmungen …
Wird übersprungen: org.videolan.VLC.Plugin.makemkv/x86_64/3-23.08 wurde bereits installiert
```

Is there another repo/github page for the updated package? Because the last update to this repo still contains the download link to the unavailable version 1.14.4

EDIT:
Okay, I can find the files under /var/lib/flatpak/runtime/org.videolan.VLC.Plugin.makemkv.
So the newest version does download the needed library files, but for some reason VLC does not use them?
I've also tried removing everything related to VLC  (also the local config files under ~/.var/app/) and then reinstall them, but still no luck

```
david@zbook-firefly14-g7:~$ flatpak list
...
VLC                        org.videolan.VLC                         3.0.19                stable      flathub  system
Bluray Java menus (BDJ) p… org.videolan.VLC.Plugin.bdj                                    3-23.08     flathub  system
MakeMKV plugin for VLC     org.videolan.VLC.Plugin.makemkv          1.17.5                3-23.08     flathub  system
...
david@zbook-firefly14-g7:~$ flatpak run org.videolan.VLC 
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
[000055b56833a6d0] main libvlc: VLC wird mit dem Standard-Interface ausgeführt. Benutzen Sie 'cvlc', um VLC ohne Interface zu verwenden.
Gtk-Message: 13:48:28.098: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:48:28.098: Failed to load module "pk-gtk-module"
Gtk-Message: 13:48:28.098: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:48:28.098: Failed to load module "pk-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Qt: Session management error: Could not open network socket
[000055b5683cfc50] main playlist: playlist is empty
aacs.c:121: No usable AACS libraries found!
dec.c:197: aacs_open() failed: -1!
[00007fdf14001130] libbluray demux: First play: 1, Top menu: 1
HDMV Titles: 105, BD-J Titles: 0, Other: 0
```

The MakeMKV flatpak itself works without any problems.

**Comment by Nukleari** [comment]
It's strange, if the files are there it should be working, I have the same version of both vlc and the plugin, the bluray menu plugin version shouldn't matter.
```
VLC                                org.videolan.VLC                    3.0.19  stable      system
Bluray Java menus (BDJ) plugin fo… org.videolan.VLC.Plugin.bdj                 3-19.08     system
MakeMKV plugin for VLC             org.videolan.VLC.Plugin.makemkv     1.17.5  3-23.08     system
```
The master branch of this repo has a really outdated version, the later versions are in branches for example at: https://github.com/flathub/org.videolan.VLC.Plugin.makemkv/tree/branch/3-23.08

**Comment by Nukleari** [comment]
One more thing, the same error occurres if you don't have a valid product key.
Make sure the key under ``~/.MakeMKV/settings.conf`` is the latest key, they change the key often through the beta.
At the moment it should be:
```
app_Key = "T-ocdqxyxgcXfTChWA2wWkv9P0QVVolgkD3GyOgZ1Z30p7t1Fm14kPcT5eIAYEneuDBx"
```

> valid until end of February 2024.
https://forum.makemkv.com/forum/viewtopic.php?t=1053

**Comment by Thalionquses** [comment]
Thanks for the clarification about where to find the newest version. Yeah it is really strange. MakeMKV works without any problems and the key is in that file. But for some reason VLV can't access the plugin. And even more strange is the fact, that on previous installs it also worked on my machine.

```
david@zbook-firefly14-g7:~$ cat ~/.MakeMKV/settings.conf 
#
# MakeMKV settings file, written by MakeMKV v1.17.5 linux(x64-release)
#

app_Key = "T-ocdqxyxgcXfTChWA2wWkv9P0QVVolgkD3GyOgZ1Z30p7t1Fm14kPcT5eIAYEneuDBx"
sdf_Stop = ""
speed_TSSTcorp_BDDVDW_SE-506CB_TS02_S1BU6YKH40020M = ""
```

**Comment by rothn** [comment]
Can verify-- I'm also having this issue. Hope we see a fix soon!

**Comment by RustyReich** [comment]
Were you ever able to figure this out? Having the same issue.

**Comment by rothn** [comment]
@RustyReich I installed a proprietary piece of software-- MakeMKV, and registered it. After running it and decrypting the blu-ray in question, it just worked. It would be nice for this to also work with my system's AACS database and system library, especially since that's free and I know how it works.
